### ISSUE TITLE
Type Error in Viewer when redirecting to external URL

### ISSUE THREAD

**Issue by teq-dev** [baptisteArno/typebot.io#50]
When implementing Logic->Redirect to an external URL, we briefly see a Type Error in the browser:

https://user-images.githubusercontent.com/90119409/169656668-8cdd8ba8-0ea9-4b71-844e-cd4a1659af5f.mp4

**Comment by teq-dev** [comment]
```
viewer:dx: Invalid `prisma.answer.upsert()` invocation:
viewer:dx: 
viewer:dx: {
viewer:dx:   where: {
viewer:dx:     resultId_blockId_stepId: {
viewer:dx: +     resultId: String,
viewer:dx: +     blockId: String,
viewer:dx: +     stepId: String
viewer:dx:     }
viewer:dx:   },
viewer:dx:   create: {
viewer:dx: +   result: {
viewer:dx: +     create?: ResultCreateWithoutAnswersInput | ResultUncheckedCreateWithoutAnswersInput,
viewer:dx: +     connectOrCreate?: ResultCreateOrConnectWithoutAnswersInput,
viewer:dx: +     connect?: ResultWhereUniqueInput
viewer:dx: +   },
viewer:dx: +   stepId: String,
viewer:dx: +   blockId: String,
viewer:dx: +   content: String,
viewer:dx: ?   createdAt?: DateTime,
viewer:dx: ?   variableId?: String | null
viewer:dx:   },
viewer:dx:   update: {}
viewer:dx: }
viewer:dx: 
viewer:dx: Argument resultId for where.resultId_blockId_stepId.resultId is missing.
viewer:dx: Argument blockId for where.resultId_blockId_stepId.blockId is missing.
viewer:dx: Argument stepId for where.resultId_blockId_stepId.stepId is missing.
viewer:dx: Argument result for create.result is missing.
viewer:dx: Argument stepId for create.stepId is missing.
viewer:dx: Argument blockId for create.blockId is missing.
viewer:dx: Argument content for create.content is missing.
viewer:dx: 
viewer:dx: Note: Lines with + are required, lines with ? are optional.
viewer:dx: 
```

**Comment by teq-dev** [comment]
Seems the redirect to external URL may be happening before the PUT and PATCH:

<img width="1073" alt="Screen Shot 2022-05-22 at 9 40 49 AM" src="https://user-images.githubusercontent.com/90119409/169698061-7afe4e98-7ec4-4511-b4ba-cc00250131a8.png">

**Comment by baptisteArno** [comment]
Couldn't reproduce with this typebot:

<img width="706" alt="CleanShot 2022-05-22 at 07 36 19@2x" src="https://user-images.githubusercontent.com/16015833/169700701-3939ff20-d5ac-4aff-861b-2e6710a129eb.png">

**Comment by teq-dev** [comment]
The Typebot in my original post above is still active if you’d like to try it. I believe the URL is visible. I’ve reproduced in self-hosted v2, v2.1.0 & in the cloud-hosted version.

**Comment by baptisteArno** [comment]
Ok, managed to reproduce. Thank you for the report 👍 

The latest commit (https://github.com/baptisteArno/typebot.io/commit/6ab0821dd865d81704b7b6835f6460b6d08561be) should resolve the issue, it will wait for the result to be updated before redirecting to a new URL.

**Comment by teq-dev** [comment]
Thank you. Your commit fixed one of the two calls. The first call, PUT is now functioning correctly before the redirect, but the PATCH is still happening after the redirect.

<img width="776" alt="Screen Shot 2022-05-22 at 4 58 53 PM" src="https://user-images.githubusercontent.com/90119409/169715552-70563693-2895-4e21-9b33-bdc4c69b89fc.png">
